workflows:
  expo-android-apk:
    name: Expo Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Set this in Codemagic environment variables
    cache:
      cache_paths:
        - node_modules
        - ~/.bun
        - ~/.expo
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          source ~/.bashrc
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Bun installed at: $(which bun)"
      - name: Install dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install --frozen-lockfile
      - name: Install Expo CLI globally with npm
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          export PATH="/usr/local/bin:$PATH"
          echo "Expo CLI installed at: $(which expo)"
          echo "EAS CLI installed at: $(which eas)"
          expo --version
          eas --version
      - name: Expo Login
        script: |
          export PATH="/usr/local/bin:$PATH"
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Error: EXPO_TOKEN environment variable is not set"
            exit 1
          fi
          expo login --non-interactive
      - name: Build Android APK with EAS
        script: |
          export PATH="/usr/local/bin:$PATH"
          eas build --platform android --profile preview --non-interactive --wait
    artifacts:
      - "*.apk"
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: true