workflows:
  # Debug APK Build - Einfach und funktionsfähig
  debug-apk:
    name: Debug APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    environment:
      vars:
        PACKAGE_NAME: "com.denaro.app"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Generate Android project
        script: |
          npx expo prebuild --platform android --clean
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Debug APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --info
      - name: List generated APK files
        script: |
          echo "Suche nach APK-Dateien..."
          find android/app/build/outputs -name "*.apk" -type f | head -10
          ls -la android/app/build/outputs/apk/debug/ || echo "Debug-Ordner nicht gefunden"
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: true
