workflows:
  expo-android-apk:
    name: Expo Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      vars:
        EXPO_TOKEN: Encrypted(...) # Add your Expo access token here
    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.expo
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
      - name: Expo Login
        script: |
          expo login --non-interactive
      - name: Build Android APK with EAS
        script: |
          eas build --platform android --profile preview --non-interactive --wait
    artifacts:
      - "*.apk"
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: true

  expo-ios:
    name: Expo iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.arbitrageswap.ai
      vars:
        EXPO_TOKEN: Encrypted(...) # Add your Expo access token here
        BUNDLE_ID: "com.arbitrageswap.ai"
        APP_ID: 1555555551
      node: 20.11.0
      npm: 10.2.4
      xcode: latest
    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.expo
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
      - name: Expo Login
        script: |
          expo login --non-interactive
      - name: Build iOS with EAS
        script: |
          eas build --platform ios --profile production --non-interactive --wait
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  expo-web:
    name: Expo Web Build
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 20.11.0
      npm: 10.2.4
    cache:
      cache_paths:
        - node_modules
        - ~/.npm
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Build web
        script: |
          npx expo export --platform web
    artifacts:
      - dist/**/*
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: false

  expo-development:
    name: Expo Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      vars:
        EXPO_TOKEN: Encrypted(...) # Add your Expo access token here
    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.expo
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: feature/*
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
      - name: Expo Login
        script: |
          expo login --non-interactive
      - name: Build development version
        script: |
          eas build --platform android --profile development --non-interactive --wait
    artifacts:
      - "*.apk"
    publishing:
      email:
        recipients:
          - daniele.latino047@gmail.com
        notify:
          success: true
          failure: false