workflows:
  # 1. Debug-Build für schnelles Testen
  debug-apk:
    name: Debug APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  # 2. Release-Build mit Expo/EAS
  expo-android-apk:
    name: Expo Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Set this in Codemagic environment variables
    cache:
      cache_paths:
        - node_modules
        - ~/.bun
        - ~/.expo
    scripts:
      - name: Setup Environment
        script: |
          npm install -g @expo/cli eas-cli
      - name: Install Dependencies
        script: npm install
      - name: Authenticate with Expo
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "EXPO_TOKEN not set"; exit 1
          fi
          eas whoami || eas login --token $EXPO_TOKEN
      - name: Build Release APK
        script: |
          eas build --platform android --profile production --non-interactive --wait
          # APK in build folder kopieren (falls vorhanden)
          find . -name "*.apk" -exec cp {} $CM_BUILD_DIR/ \;
    artifacts:
      - "*.apk"
